### ISSUE TITLE
Heracles viewer gets hung on glass at load

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Heracles#12]
Several times as I'm working through the Heracles viewer, on entry to the page, I find that I can't click on any item, like there's a div blocking my activities which does not go away.  I have to refresh the page several times before that glass div goes away.  Is there a way to get more consistent performance with that?

**Comment by jduke99** [comment]
Patrick, is this after submitting an analysis job (i.e., on runner)?  Or is this when it is loading up a visualization (i.e., on viewer)?

**Comment by pbr6cornell** [comment]
Both

**Comment by charhart** [comment]
Are things loading, and the div just not going away? Or are things loading very slowly?

Are you running in Olympus? Or standalone Heracles?

**Comment by charhart** [comment]
Just committed something that lets you run in background (can click out of modal).

**Comment by charhart** [comment]
I also created a pull request on WebAPI to create the indexes with flyway. Once that gets merged and deployed, it should make everything much faster.

https://github.com/OHDSI/WebAPI/pull/43

**Comment by charhart** [comment]
Alright, the indexes have been merged into WebAPI, so both Heracles and WebAPI should be redeployed to pick up these 2 changes.
